### ISSUE TITLE
Workstation/developer specific resources should not be present in git

### ISSUE THREAD

**Issue by geoffroya** [iay/mdq-server#50]
Hi @iay 
Shouldn't specific resources linked to IDE/developer workstation be stripped of the repo?

**Comment by iay** [comment]
I don't normally commit purely developer-specific things, and I don't think I have here.

As to IDE configurations, I do find it useful to commit those for Eclipse because there's really no way to keep them consistent between developers otherwise. Not everything you want to preserve can be POM-derived, unfortunately.

Can you be more specific about the resources you're concerned about?

**Comment by geoffroya** [comment]
Of course. What I use to exclude:
- .settings/
- .project
- .classpath

All this is created by Eclipse during project import, and I saw several times those files changing from one developer to the other, causing mess to others.
The only thing I find useful, but requires to be set once, is the code formatter, so that anyone commmiting respect the project formatting rules.

**Comment by iay** [comment]
Formatting and warnings are the important things that aren't part of the Eclipse import process and need to be carried across from one developer to another. Unfortunately Eclipse doesn't separate these at all well.

The conventions I use for most of my projects (including this one) are derived from the conventions I use in my Shibboleth project work: we include the Eclipse settings in repositories, and also have a master set that we periodically copy over selected files when conventions change. Yes, it sometimes causes a little mess when Eclipse decides to update things on its own, but we've found this approach to be better than the alternatives for our purposes.

I'll be continuing with those conventions for this project, so I will close this issue now. Thanks for the suggestions, though.
