### ISSUE TITLE
mvn clean install fails out of the box

### ISSUE THREAD

**Issue by geoffroya** [iay/mdq-server#51]
Tests fail during clean install.
After updating parent version (11.1.0-SNAPSHOT is no more available), I tried the following without success:
`mvn clean install`
`mvn clean install -Prelease`

```
[ERROR] Cannot instantiate class uk.org.iay.mdq.server.EntitiesControllerTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
```

Any clue?

**Comment by iay** [comment]
I can confirm that this is happening for me as well. I'll look into it, thanks for the report.

**Comment by iay** [comment]
This one is a bit strange. It seems as if something changed in Spring Framework 5.2.8 --> 5.2.9 in October which broke some of these tests by removing a field somewhere.

I will need to dig into this a bit more deeply to understand why this is failing but the metric tonne of similar code in the Shibboleth projects doesn't. In the meanwhile, if you just want to make progress, you could try adding this to the `<properties>` section of `pom.xml`:

```xml
        <spring.version>5.2.8.RELEASE</spring.version>
```

At least for me, that gets the tests working again.

**Comment by iay** [comment]
Turned out to be a dependency mismatch introduced because the `spring-test` dependency was versioned in one way, the other Spring Framework dependencies in another (via Spring Boot). Commit 57db834 brings them together, at the penalty of using an older version of Spring Framework than the rest of the Shibboleth stack wants; it shouldn't affect us, though.

I really need to upgrade to Spring Boot 2.4.x to resolve this properly, but I will make a separate issue for that.
